### PR TITLE
Update from dpericated opencv API

### PR DESCRIPTION
**Pull request by ruffsl**
Fixes https://github.com/MIT-SPARK/Kimera-VIO/issues/60

### CODE REVIEW

**Comment by ToniRV** [comment]
Nice, seems like very small changes, is this OpenCV 3.3.1 backwards compatible?

**Comment by ruffsl** [comment]
I'm not sure. Do you see a way this could support both? Looks like headers massage have changed between the two and we may just need some if defs.

**Comment by akashsharma02** [comment]
Is there any plan on getting this merged, looks like there was some problem with OpenCV installation in the docker environment? If not I can submit another PR for this. 
Also, I do not think OpenCV 4 is backwards compatible with OpenCV 3, because the anonymous enums used have been redefined now.

**Comment by ruffsl** [comment]
@akashsharma02 , do you see anything else this might need?

**Comment by akashsharma02** [comment]
I'm actually not sure since the failure was a build issue with OpenCV. I have a fork with the minor changes I've made, maybe you can take a look at that.

**Comment by ToniRV** [comment]
Closing as #100 allows for OpenCV 3 & 4, thanks!

**Pull request closed without merging**
